import{a as L,S as C,i as s}from"./assets/vendor-CrlV4O_2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const v="50555446-a2cf9db12dc2e06100b3b332c",E="https://pixabay.com/api/",u=15;async function g(t,e=1){const r={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:u};return(await L.get(E,{params:r})).data}const h=document.getElementById("gallery"),B=document.getElementById("load-more-btn");function p(t){const e=t.map(r=>`
      <li>
        <a href="${r.largeImageURL}" class="gallery-item" title="${r.tags}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${r.likes}</p>
            <p class="info-item"><b>Views:</b> ${r.views}</p>
            <p class="info-item"><b>Comments:</b> ${r.comments}</p>
            <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
          </div>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",e)}function I(){h.innerHTML=""}function f(t){B.classList.toggle("hidden",!t)}const $=document.getElementById("form"),M=document.getElementById("search-input"),l=document.getElementById("loader"),y=document.getElementById("gallery"),S=document.getElementById("load-more-btn");let a="",i=1,m=0;const b=new C(".gallery a");$.addEventListener("submit",async t=>{if(t.preventDefault(),a=M.value.trim(),!a){s.warning({message:"The search field cannot be empty!",position:"bottomCenter",backgroundColor:"red",messageColor:"white"});return}i=1,I(),f(!1),l.classList.remove("hidden");try{const e=await g(a,i);if(m=e.totalHits,e.hits.length===0){s.info({message:"Sorry, no images match your search query.",position:"bottomCenter",backgroundColor:"red",messageColor:"white"});return}p(e.hits),b.refresh(),m>u&&window.addEventListener("scroll",w)}catch(e){s.error({message:"An error occurred while retrieving images",position:"bottomCenter",backgroundColor:"red",messageColor:"white"}),console.error(e)}finally{l.classList.add("hidden")}});S.addEventListener("click",async()=>{i+=1,l.classList.remove("hidden");try{const t=await g(a,i);p(t.hits),b.refresh();const e=Math.ceil(m/u);i>=e&&(f(!1),s.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter",backgroundColor:"red",messageColor:"white"})),H()}catch(t){s.error({message:"Failed to load more images",position:"bottomCenter",backgroundColor:"red",messageColor:"white"}),console.error(t)}finally{l.classList.add("hidden")}});function H(){const{height:t}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function w(){const{bottom:t}=y.getBoundingClientRect(),e=window.innerHeight;t<=e&&(f(!0),window.removeEventListener("scroll",w))}
//# sourceMappingURL=index.js.map
